### ISSUE TITLE
Upload library to a CDN

### ISSUE THREAD

**Issue by PatMyron** [LexmarkWeb/csi.js#15]
It'd be awesome if this was uploaded to a CDN, so everyone didn't have to copy and host their own version of this file themselves, and could just add a line like 
`<script src="https://cdnjs.cloudflare.com/ajax/libs/csi/1.0.0/csi.min.js"></script>` 
to their files to use this.

[cdnjs](https://cdnjs.com) is a popular free and open source public CDN, and I'm sure there are plenty of others that would work

Thanks!

**Comment by MartinKolarik** [comment]
You can find all files hosted at https://cdn.jsdelivr.net/gh/LexmarkWeb/csi.js/

**Comment by PatMyron** [comment]
that's awesome!

Could you add that to the README?
